### ISSUE TITLE
Simply fails on gmail :(

### ISSUE THREAD

**Issue by redpola** [mihaip/mail-trends#1]
$ python main.py --server=imap.gmail.com --use_ssl --username=blah@gmail.com --me=blah@gmail.com --skip_labels
[2013-05-09 13:07:47,781] Initializing
Password for blah@gmail.com: 
[2013-05-09 13:07:50,888] Connecting
[2013-05-09 13:07:51,719] Logging in
[2013-05-09 13:07:52,231] Selecting mailbox '[Gmail]/All Mail'
Traceback (most recent call last):
  File "main.py", line 251, in <module>
    message_infos = GetMessageInfos(opts)
  File "main.py", line 54, in GetMessageInfos
    m.SelectAllMail()
  File "/Users/neil/Work/Code/mail-trends/mail.py", line 60, in SelectAllMail
    self.SelectMailbox(MAILBOX_GMAIL_ALL_MAIL)
  File "/Users/neil/Work/Code/mail-trends/mail.py", line 65, in SelectMailbox
    self.__AssertOk(r)
  File "/Users/neil/Work/Code/mail-trends/mail.py", line 193, in __AssertOk
    assert response == "OK"
AssertionError

**Comment by redpola** [comment]
Ok, more info now I'm in a position to collect it...

scrape:mail-trends neil$ python -V
Python 2.7.2
scrape:mail-trends neil$ uname -a
Darwin scrape.local 12.3.0 Darwin Kernel Version 12.3.0: Sun Jan  6 22:37:10 PST 2013; root:xnu-2050.22.13~1/RELEASE_X86_64 x86_64

It seems a fix to get this working on OS X is:

@@ -6,8 +6,8 @@ import cache
 import messageinfo
 import stringscanner

-MAILBOX_GMAIL_ALL_MAIL = "[Gmail]/All Mail"
-MAILBOX_GMAIL_PREFIX = "[Gmail]"
+MAILBOX_GMAIL_ALL_MAIL = "INBOX"
+MAILBOX_GMAIL_PREFIX = "INBOX"

 class Mail(object):
   def **init**(self, server, use_ssl, username, password,
