### ISSUE TITLE
Crash when finding "me" emails

### ISSUE THREAD

**Issue by signal15** [mihaip/mail-trends#7]
This was run against an MS Exchange account.  MAILBOX_GMAIL...  variables were both changed to "INBOX".  Here's the error:

[2015-10-14 17:36:48,550] Identifying "me" messages
Traceback (most recent call last):
  File "./main.py", line 251, in <module>
    message_infos = GetMessageInfos(opts)
  File "./main.py", line 94, in GetMessageInfos
    name, address = message_info.GetSender()
  File "/Users/xxx/mail-trends/messageinfo.py", line 67, in GetSender
    return self._GetNameAddress("from")
  File "/Users/xxx/mail-trends/messageinfo.py", line 94, in _GetNameAddress
    if not header in self.headers:
AttributeError: 'MessageInfo' object has no attribute 'headers'

**Comment by signal15** [comment]
I have a fix.  It works, but no idea if it's just covering up a larger problem.  Add to line 94 of messageinfo.py before "if not header in self.headers:"

  if not hasattr(self, 'headers'):
      return None, None
